language: python
python:
  - "2.7"
before_install: cd server
install:
  - npm install -g serverless
  - python -m pip install -r requirements.txt -t .
before_script: cd server
script: python -m unittest discover -p "*_test.py"
deploy: sls deploy