sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - npm install -g serverless
  - npm install -g serverless-python-requirements
  - cd src
install:
  - pip install coveralls
  - pip install -r requirements.txt
before_script:
  - python -m unittest discover -p "*_test.py"
  - python -m coverage run -m unittest discover -p "*_test.py"
  - coveralls
script:
  - sls plugin install -n serverless-python-requirements
  - sls deploy