service: kartskill

provider:
  name: aws
  runtime: python3.6
  stage: ${env:DEPLOY_ENV}
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    MARIO_MONGO_URI: ${env:MARIO_MONGO_URI}
    MARIO_MONGO_DB: ${env:MARIO_MONGO_DB}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  slack:
    handler: api/slack.handle
    events:
      - http:
          path: slack
          method: post

  create_player:
    handler: api/player.create
    events:
      - http:
          path: api/player
          method: post
          cors: true

  list_players:
    handler: api/player.all
    events:
      - http:
          path: api/player
          method: get
          cors: true

  get_player:
    handler: api/player.get
    events:
      - http:
          path: api/player/{id}
          method: get
          cors: true

  update_player:
    handler: api/player.update
    events:
      - http:
          path: api/player/{id}
          method: put
          cors: true

  delete_player:
    handler: api/player.delete
    events:
      - http:
          path: api/player/{id}
          method: delete
          cors: true

  create_game:
    handler: api/game.create
    events:
      - http:
          path: api/game
          method: post
          cors: true

  list_games:
    handler: api/game.all
    events:
      - http:
          path: api/game
          method: get
          cors: true

  get_game:
    handler: api/game.get
    events:
      - http:
          path: api/game/{id}
          method: get
          cors: true

  update_game:
    handler: api/game.update
    events:
      - http:
          path: api/game/{id}
          method: put
          cors: true

  delete_game:
    handler: api/game.delete
    events:
      - http:
          path: api/game/{id}
          method: delete
          cors: true

  create_character:
    handler: api/character.create
    events:
      - http:
          path: api/character
          method: post
          cors: true

  list_characters:
    handler: api/character.all
    events:
      - http:
          path: api/character
          method: get
          cors: true

  get_character:
    handler: api/character.get
    events:
      - http:
          path: api/character/{id}
          method: get
          cors: true

  update_character:
    handler: api/character.update
    events:
      - http:
          path: api/character/{id}
          method: put
          cors: true

  delete_character:
    handler: api/character.delete
    events:
      - http:
          path: api/character/{id}
          method: delete
          cors: true

  get_average_ranking:
    handler: api/ranking.average
    events:
      - http:
          path: api/ranking/average
          method: get
          cors: true

  get_skill_ranking:
    handler: api/ranking.skill
    events:
      - http:
          path: api/ranking/skill
          method: get
          cors: true