service: kartskill

provider:
  name: aws
  runtime: python3.6
  stage: dev
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    MARIO_MONGO_URI: ${env:MARIO_MONGO_URI}
    MARIO_MONGO_DB: ${env:MARIO_MONGO_DB}
    PLOTLY_USERNAME: ${env:PLOTLY_USERNAME}
    PLOTLY_API_KEY: ${env:PLOTLY_API_KEY}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  slack:
    handler: slack_handler.handle
    events:
      - http:
          path: slack
          method: post

  create:
    handler: api_person.create
    events:
      - http:
          path: api/person
          method: post
          cors: true

  list:
    handler: api_person.list
    events:
      - http:
          path: api/person
          method: get
          cors: true

  get:
    handler: api_person.get
    events:
      - http:
          path: api/person/{id}
          method: get
          cors: true

  update:
    handler: api_person.update
    events:
      - http:
          path: api/person/{id}
          method: put
          cors: true

  delete:
    handler: api_person.delete
    events:
      - http:
          path: api/person/{id}
          method: delete
          cors: true
